### ISSUE TITLE
1.2.0语法错误

### ISSUE THREAD

**Issue by vzina** [hyperf/engine#4]
PHP Parse error:  syntax error, unexpected 'bool' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in vendor/hyperf/engine/src/Channel.php on line 20

**Comment by limingxinleo** [comment]
php 什么版本
swoole 什么版本

**Comment by vzina** [comment]
PHP 7.3.22
Swoole 4.6.7

应该是你们代码用了高版本的语法，导致不兼容了。。。

**Comment by limingxinleo** [comment]
支持 7.3 啊

https://github.com/hyperf/engine/runs/4664747642?check_suite_focus=true

**Comment by limingxinleo** [comment]
woc 好吧

不支持 7.3

**Comment by limingxinleo** [comment]
1.2.0 我删掉了

你重新安装试试，如果还不行就直接锁版本吧

composer require "hyperf/engine:1.1.*"

**Comment by vzina** [comment]
> 1.2.0 我删掉了
> 
> 你重新安装试试，如果还不行就直接锁版本吧
> 
> composer require "hyperf/engine:1.1.*"

好的！
